spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitcourse?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    kafka:
      producer:
        bootstrap-servers: 127.0.0.1:9092

      bootstrap-servers: 127.0.0.1:9092

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  secret: b3c63a3b79900b5dc53a0013a81fe1309eb0aa056900020476558e5bc36c52ed
  expiration_time: 86400000  # 1일